### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by chenshuai2144** [ant-design/ant-design-pro-layout#1]
- [x] 💪 add test and ui test
- [x] 👀better api doc
- [x] 👀have a site
- [x] 💪add [ create-react-app](https://github.com/facebook/create-react-app) use doc
- [x] 💪add  old project use doc
Maybe with and without umi

**Comment by iloveip** [comment]
Hi there,

Do you have an example of create-react-app with pro-layout?

**Comment by forvenus** [comment]
> Hi there,
> 
> Do you have an example of create-react-app with pro-layout?

yes, create-react-app example please, better without umi
